require:
  - ./cops/custom/disallow_postgres_time_functions.rb

plugins:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  NewCops: enable

Capybara/ClickLinkOrButtonStyle:
  Enabled: false

Custom/DisallowPostgresTimeFunctions:
  Enabled: true

Layout/FirstArrayElementLineBreak:
  Enabled: true

Layout/FirstHashElementLineBreak:
  Enabled: true

Layout/FirstMethodArgumentLineBreak:
  Enabled: true

Layout/FirstMethodParameterLineBreak:
  Enabled: true

Layout/LineLength:
  Max: 140

Layout/MultilineArrayLineBreaks:
  Enabled: true

Layout/MultilineHashKeyLineBreaks:
  Enabled: true

Layout/MultilineMethodArgumentLineBreaks:
  Enabled: true

Layout/MultilineMethodParameterLineBreaks:
  Enabled: true

# https://docs.rubocop.org/rubocop/cops_metrics.html#metricsabcsize
Metrics/AbcSize:
  Max: 30

# https://docs.rubocop.org/rubocop/cops_metrics.html#metricsblocklength
Metrics/BlockLength:
  AllowedMethods:
  - included
  Exclude:
  - 'config/**/*'

Metrics/ClassLength:
  Max: 200

# https://docs.rubocop.org/rubocop/cops_metrics.html#metricsmethodlength
Metrics/MethodLength:
  Max: 25

Metrics/ModuleLength:
  Max: 200

Metrics/ParameterLists:
  Max: 7

# https://docs.rubocop.org/rubocop-rails/cops_rails.html#railsi18nlocaletexts
Rails/I18nLocaleTexts:
  Enabled: false

Rails/StrongParametersExpect:
  Enabled: false

# https://docs.rubocop.org/rubocop-rails/cops_rails.html#railsunknownenv
Rails/UnknownEnv:
  Environments:
    - development
    - test
    - test_integ
    - production
    - staging

# https://docs.rubocop.org/rubocop-rspec/cops_rspec.html#rspecdescribeclass
RSpec/DescribeClass:
  Exclude:
    - 'spec/{requests,system}/**/*'

# https://docs.rubocop.org/rubocop-rspec/cops_rspec.html#rspecexamplelength
RSpec/ExampleLength:
  Max: 25

# https://docs.rubocop.org/rubocop-rspec/cops_rspec.html#rspecimplicitsubject
RSpec/ImplicitSubject:
  EnforcedStyle: single_statement_only

# https://docs.rubocop.org/rubocop-rspec/cops_rspec.html#rspecmultipleexpectations
RSpec/MultipleExpectations:
  Exclude:
  - 'spec/{requests,system}/**/*'

# https://docs.rubocop.org/rubocop-rspec/cops_rspec.html#rspecmultiplememoizedhelpers
RSpec/MultipleMemoizedHelpers:
  Max: 20

# https://docs.rubocop.org/rubocop-rspec/cops_rspec.html#rspecnestedgroups
RSpec/NestedGroups:
  Max: 7

# https://docs.rubocop.org/rubocop-rspec/cops_rspec.html#rspecpending
RSpec/Pending:
  Enabled: true

# https://docs.rubocop.org/rubocop/cops_style.html#styledocumentation
Style/Documentation:
  Enabled: false

# https://docs.rubocop.org/rubocop/cops_style.html#stylefetchenvvar
Style/FetchEnvVar:
  Enabled: false

# https://docs.rubocop.org/rubocop/cops_style.html#stylefrozenstringliteralcomment
Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: always

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
